name: Quasar-Pulsar
on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, world"
